[tool.poetry]
name = "shiftago-qt"
version = "0.1.0"
description = ""
authors = ["Thomas Schaper <tschaper69@gmail.com>"]
readme = "README.md"
packages = [{include = "shiftago_qt"}]

[tool.poetry.dependencies]
python = "^3.10"
pyqt5 = "^5.15.9"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
