[tool.poetry]
name = "shiftago-qt"
version = "0.1.0"
description = ""
authors = ["Thomas Schaper <tschaper69@gmail.com>"]
readme = "README.md"
packages = [{include = "shiftago_qt"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
python-statemachine = "^2.1.2"
pyside2 = "^5.15.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
